### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by NiKiZe** [sisve/openconnect-wrapper#1]
No license is specified, would it be appropriate to use same license as OpenConnect itself?

Tack på förhand!

**Comment by sisve** [comment]
Hi,

Once I started looking into it I realized two things:

- The C# code dynamically loads OpenConnect (LGPL v2.1) using [DllImport]
- The C code has no interaction with OpenConnect at all, it's only a wrapper to handle varargs used for logging callbacls.
- The vpnc scripts are GPL v2 (or later) (ref: https://gitlab.com/openconnect/vpnc-scripts), and these are both redistributed (embedded into the executable) and the Windows one is also modified.

It's my understanding that this repo would need to be GPL v2 (or later) due to the vpnc scripts.

Before I commit the license file; do you agree with my thought process? Or am I missing something?

Mvh Simon

**Comment by NiKiZe** [comment]
Yes I agree, GPLv2 is probably the only option.
Maybe there needs to be additional notice of who holds the Copyright for which part?

**Comment by sisve** [comment]
I've added both a GPL v2 license file, and a text notice at the bottom of the readme. Do you think I need to do anything more, or can I mark this issue as completed?

**Comment by NiKiZe** [comment]
I think that is good enough for now.
Consider adding Copyright notice to program startup banner, for the binary releases, but could try to investigate further what is best there, and in the meantime close this as fixed.

**Comment by sisve** [comment]
I added short startup banner mentioning where the source can be found. I'm closing this issue, I think this is good-enough for now.
